# Use SDK image for the build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /App

# Install dotnet-ef globally
RUN dotnet tool install -g dotnet-ef

# Set PATH to include dotnet tools
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -c Release -o out

# Expose the port the app runs on
EXPOSE 5277

# Set environment variables
ENV ASPNETCORE_HTTP_PORTS=5277
ENV ASPNETCORE_URLS=http://*:5277
ENV ASPNETCORE_POSTGRES_HOST=postgres
ENV ASPNETCORE_POSTGRES_PORT=5432
ENV ASPNETCORE_POSTGRES_DATABASE=postgres
ENV ASPNETCORE_POSTGRES_USER=postgres
ENV ASPNETCORE_POSTGRES_PASSWORD=postgres

ENTRYPOINT ["dotnet", "run"]